// Auto-generated from database table `Permission`.
// Do not edit manually. Run `npm run prisma:generate` to regenerate.

export type Permission =
  | "administrator:permission:create"
  | "administrator:permission:view"
  | "administrator:permissiongroup:create"
  | "administrator:role:create"
  | "administrator:role:update"
  | "administrator:role:view"
  | "administrator:users:create"
  | "administrator:users:management"
  | "administrator:users:update"
  | "administrator:users:view"
  | "case:assign"
  | "case:create"
  | "case:delete"
  | "case:update"
  | "case:update:items"
  | "case:view"
  | "storage:item:create"
  | "storage:item:delete"
  | "storage:item:update"
  | "storage:item:view"
  | "storage:location:create"
  | "storage:location:delete"
  | "storage:location:update"
  | "storage:location:view"
  | "storage:unit:create"
  | "storage:unit:delete"
  | "storage:unit:update"
  | "storage:unit:view"
  | "storage:vendor:create"
  | "storage:vendor:delete"
  | "storage:vendor:update"
  | "storage:vendor:view";
