apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reverse-proxy
  template:
    metadata:
      labels:
        io.kompose.service: reverse-proxy
    spec:
      containers:
        - image: nginx:alpine
          name: reverse-proxy
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-config
          name: nginx-config
