apiVersion: v1
kind: Secret
metadata:
  labels:
    io.kompose.service: backend
  name: backend-secret
type: Opaque
stringData:
  ACCESS_TOKEN_SECRET: REPLACE_WITH_ACCESS_TOKEN_SECRET
  DATABASE_URL: REPLACE_WITH_DATABASE_URL
  REFRESH_TOKEN_SECRET: REPLACE_WITH_REFRESH_TOKEN_SECRET
