apiVersion: v1
data:
  nodemon.json: |
    {
      "watch": ["src", "schemas"],
      "ext": "ts,json",
      "ignore": ["src/**/*.spec.ts", "src/tests/**"],
      "env": { "TS_NODE_PROJECT": "tsconfig.build.json" },
      "exec": "tsx watch -r tsconfig-paths/register ./src/index.ts"
    }
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend
  name: backend-nodemon
