apiVersion: v1
kind: Secret
metadata:
  labels:
    io.kompose.service: cloudflare-tunnel
  name: cloudflare-tunnel-secret
type: Opaque
stringData:
  CLOUDFLARE_TUNNEL_TOKEN: REPLACE_WITH_CLOUDFLARE_TUNNEL_TOKEN
